http_server:
  address: "localhost:8080"

database:
  user: "hitalent"
  password: "hitalent"
  host: "localhost"
  port: 5432
  name: "hitalent"

logger:
  logfile: "log.txt" # filename or "stdout"
  loglevel: "debug"  # debug, warn, info, error